/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2025-05-04 21:21:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.tagplugins.jstl.core.Import;
import java.util.*;
import com.sample.core.domain.Pizza;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.Import");
    _jspx_imports_classes.add("com.sample.core.domain.Pizza");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<title>PIZZERIA</title>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tvar contextPath=\"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/scripts-barcito.js\"></script>\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/logout.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/eliminarPizza.js\"> </script>\r\n");
      out.write("\t<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t");

	    String rol = (String) session.getAttribute("ROL_USUARIO");
	    if ("ADMIN".equals(rol)) {
	    	
	
	
      out.write("\r\n");
      out.write("\t    <p>Hola Admin, podés ver esto.</p>\r\n");
      out.write("\t    <!-- O poner botones, secciones, lo que quieras -->\r\n");
      out.write("\t");

	    }
	
      out.write("\r\n");
      out.write("\t<p>Rol detectado: ");
      out.print( rol );
      out.write("</p>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"alert alert-block\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"recent_order\">\r\n");
      out.write("\t\t\t\t<h1>Pedidos </h1>\r\n");
      out.write("\t\t  <button type=\"button\" class=\"btn btn-primary\" id=\"btn-logout\">Log Out</button>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<table id=\"boxPedidosSolicitados\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"25%\">Fecha</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"12%\" class=\"center\">Identificador</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"12%\" class=\"center\">Direccion</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"12%\" class=\"center\">Estado</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"12%\" class=\"center\">Telefono</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"12%\" class=\"center\">Monto</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"12%\" class=\"center\">Ver detalles</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" class=\"fecha\">test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"12%\" class=\"identificador\">test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" class=\"direccion\">test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" class=\"estado\">test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" class=\"teï¿½efono\">test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" class=\"monto\">test</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" class=\"detalles\"></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-light bg-light mt-4\">\r\n");
      out.write("\t  <a class=\"navbar-brand\" href=\"#\">Productos</a>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<div class=\"card-group homeitem mt-4\" 1>\r\n");
      out.write("\t\t<div class=\"card m-2\" >\r\n");
      out.write("\t\t  <img class=\"card-img-top\" src=\"https://cdn.pixabay.com/photo/2023/05/31/11/15/fish-8031138_960_720.jpg\" alt=\"Card image cap\">\r\n");
      out.write("\t\t  <div class=\"card-body\">\r\n");
      out.write("\t\t    <h5 class=\"card-title\">Pizza</h5>\r\n");
      out.write("\t\t    <p class=\"card-text\">Pizza disponibles</p>\r\n");
      out.write("\t\t    <a href=\"");
      out.print( request.getContextPath());
      out.write("/LeerDatosPizza\" class=\"btn btn-primary\">Ir</a>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav class=\"navbar navbar-light bg-light\">\r\n");
      out.write("\t  <a class=\"navbar-brand\" href=\"#\">Mesas</a>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"card-group homeitem mt-4\"  id=\"boxGroupMesas\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
